# 1. Identificación del Microservicio
spring.application.name=ms-usuarios
server.port=8085

# 2. Configuración de la Base de Datos (H2 en memoria para pruebas rápidas)
spring.datasource.url=jdbc:h2:mem:usuariosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 3. Configuración de JPA / Hibernate
# "update" crea las tablas automáticamente basado en tu clase Usuario.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 4. Consola H2 (Para que puedas ver los datos en el navegador)
# Podrás entrar en: http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 5. Desactivar seguridad por defecto de Spring (Opcional si quieres probar sin JWT aún)
# Esto permite que no te pida una contraseña aleatoria en la consola al iniciar
spring.main.allow-bean-definition-overriding=true

spring.cloud.config.enabled=false