server.port=8085

# Conexión a tu nueva base de datos en AWS RDS
spring.datasource.url=jdbc:postgresql://fireforce.c1w28coqqryx.us-east-1.rds.amazonaws.com:5432/postgres

# Credenciales de acceso
spring.datasource.username=Fireforce
spring.datasource.password=admin123

# Configuración del Driver y JPA/Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
app.jwt.expiration=86400000